### ISSUE TITLE
Import the highlight languages asynchronously on demand

### ISSUE THREAD

**Issue by aminya** [wooorm/lowlight#32]
The size of the lowlight package is almost 900KB (minified!) because it imports all the highlight languages at the top of the module. This means that any package that uses lowlight should pay a huge penalty. 

`emphasize` is among one of those packages which are huge because of this

**Comment by wooorm** [comment]
You can use `core.js` if you don’t want any languages, and manually add them. This was explained in the [readme](https://www.npmjs.com/package/lowlight#browser), but I removed it a couple days ago because I’m working on the next version which will use a smaller bundle by default. This [landed on main](https://github.com/wooorm/lowlight/commit/95cd2f631a8a629ae00efff2d8fc8c5759a0fb5a) already.
It’ll be released when highlight.js’ next major is released, which is soonish.

**Comment by joshgoebel** [comment]
> which is soonish.

If we can find help reviewing PRs.... :-)
