### ISSUE TITLE
Add position information to tokens

### ISSUE THREAD

**Issue by segevfiner** [wooorm/lowlight#52]
It could be cool to add position information as specified by https://github.com/syntax-tree/unist to the resulting HAST.

**Comment by wooorm** [comment]
Heya!

What do you plan on using that for?

To do that, we’d have to only add it to the text nodes, because the text *is* preset in the original file, but we wouldn’t add them to the elements, as those aren‘t written in the original source. In unist terms, the elements are [*generated*](https://github.com/syntax-tree/unist?tab=readme-ov-file#generated)

**Comment by smith-kyle** [comment]
This would be helpful for me too! I'd be able to apply diff highlights to the tree if I knew what the source positions

**Comment by wooorm** [comment]
Can you explain?

**Comment by wooorm** [comment]
The notebook diff tool, with just lowlight, that sounds like an okay reason to have this.

But the second part, using lowlight inside unified for markdown -> html, and transforming it, in that case the positional info should not be there.
Positions refer to places *in the source file*. But the `<span>`s being generated *are not in the source file*. Across unified, when tools generate nodes, they don’t have positional info.
From earlier, the “In unist terms, the elements are [generated](https://github.com/syntax-tree/unist#generated)”
